server:
  servlet:
    context-path: /
  port: 8080
  compression:
    mime-types:
      - application/json

spring:
  application:
    name: subscription-service
  main:
    allow-bean-definition-overriding: true
#Remove this feature to enable database connections
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  liquibase:
    enabled: false
##  --------

# Enabling database connection
datasource:
  url: jdbc:postgresql://localhost:<port>/<db>
  username: subscription
  password: subscription
  continue-on-error: true
jpa:
  open-in-view: false
  show-sql: true
  format-sql: true
  hibernate:
    ddl-auto: update
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  properties:
    hibernate:
      jdbc:
        batch_size: 50

## Enable liquidbase

liquibase:
  enabled: true
  change-log: classpath:db/changelog/changelog-local.xml

## Enabling rabbitmq

#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: <username>
#    password: <password>
#    cache:
#      connection:
#        mode: CONNECTION
#      channel:
#        size: 50
#      checkout-timeout: 10000
