server:
  servlet:
    context-path: /
  port: 8080
  compression:
    mime-types:
      - application/json

spring:
  application:
    name: subscription-service
  main:
    allow-bean-definition-overriding: true
#Remove this feature to enable database connections
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      -
  # Enabling database connection
  datasource:
    url: jdbc:mysql://localhost:3306/subscription
    username: root
    password: subscription
    driver-class-name:  com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.mysql
    properties:
      hibernate:
        jdbc:
          batch_size: 50
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/subscription
    username: root
    password: subscription
    driver-class-name:  com.mysql.jdbc.Driver
    schemas: subscription

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: subscription
    password: subscription
    cache:
      connection:
        mode: CONNECTION
      channel:
        size: 50
      checkout-timeout: 10000
  
config:
  technical-visit:
    url: http://localhost:9081
    queue:
      out: shedule_technical_visit
    

